[package]
name = "fang"
version = "0.1.0"
authors = ["Ayrat Badykov <ayratin555@gmail.com>"]
edition = "2018"
description = "fang is in active development. it's published to take the name on crates.io"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.6", features = ["postgres", "serde_json", "chrono", "uuidv07"] }
diesel-derive-enum = { version = "1", features = ["postgres"] }
dotenv = "0.15.0"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
serde_json = "1.0"
typetag = "0.1"
serde = { version = "1.0", features = ["derive"] }
